spring.application.name=employee_managment
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_sys
spring.datasource.username=postgres
spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=ce4c83ffdf89e7f6286fa3cfd150fc98afcd6e72fe16e40f8395299129eab2c8
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=8905549e62119c
spring.mail.password=48dd1ba97a077d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
